<a href="https://colab.research.google.com/github/angi219/Works_and_Presentation/blob/main/n111a_EDA(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src='https://i.imgur.com/RDAD11M.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 1 / NOTE 1*

---

# 📝 Assignment

# **🌱 기본 과제**

## **Part 1. EDA**

### **1-1. 데이터셋 불러오기**

우리는 이 과제를 통해 아래의 url에 존재하는 Travel.xlsx를 Pandas의 데이터프레임으로 가져와 데이터에서 의미를 도출하고자 합니다. 
- https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/stocks/Travel.xlsx

유의해야 할 점은 데이터를 불러올때, 그 파일의 형태와 구조에 따라 올바르게 불러와야 한다는 점입니다. <br> 

우선, 이 파일은 `.csv` 형태가 아닌 `.xlsx` 파일 형태입니다. 그러므로 Pandas의 `read_csv` 메서드가 아닌 `read_excel` 메서드를 활용하여 데이터를 가져와야 합니다. 또한, 이 파일은 2개의 시트로 구성되어 있으며 시트명은 각각 `008770` , `035250` 입니다. <br>

아래의 코드 Tip과 첨부된 링크를 활용하여 각 시트의 데이터가 다음 이미지와 같은 데이터프레임 형식을 갖도록 만드세요.

<img src='https://i.imgur.com/G1rLOnh.png'>

- `008770` 시트의 데이터는 **df1**으로, `035250` 시트의 데이터는 **df2**로 저장합니다.

<br>

> **💡 Tip**
1. df = pd[.read_excel](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)(url, sheet_name = 0)
2. df = df[.T](https://pandas.pydata.org/pandas-docs/version/0.25.0/reference/api/pandas.DataFrame.T.html)
3. df_columns = df1[.loc](https://stackoverflow.com/questions/31593201/how-are-iloc-and-loc-different)[0]
4. df[.columns](https://stackoverflow.com/questions/31328861/python-pandas-replacing-header-with-top-row) = df_columns
5. df = df[1:]

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#pandas 및 기타 플러그인을 이 시트에 포함하고, 약어를 지칭한다.

In [2]:
#read_excel(url)을 이용하려고 하나, https':'에 오류 구문이 검출되는 탓에 일단 파일 업로드 형식으로 변경함.
from google.colab import files
uploaded = files.upload()

Saving Travel.xlsx to Travel.xlsx

In [3]:
#Travel.xlsx 파일을 pandas의 읽기 문법으로 head 표시됨.
df1 = pd.read_excel('Travel.xlsx', sheet_name = 0)
df1.head()

,주요재무정보,2019/09\n(IFRS연결),2019/12\n(IFRS연결),2020/03\n(IFRS연결),2020/06\n(IFRS연결),2020/09\n(IFRS연결),2020/12(E)\n(IFRS연결),2021/03(E)\n(IFRS연결),2021/06(E)\n(IFRS연결)
0,매출액,14753.0,15440.0,9437.0,5230.0,8795.0,9980.0,9761.0,9820.0
1,영업이익,574.0,776.0,-668.0,-634.0,-198.0,50.0,144.0,265.0
2,영업이익(발표기준),574.0,776.0,-668.0,-634.0,-198.0,NaN,NaN,NaN
3,세전계속사업이익,376.0,538.0,-925.0,-819.0,-366.0,-109.0,14.0,172.0
4,당기순이익,274.0,380.0,-736.0,-677.0,-285.0,-100.0,71.0,214.0

In [6]:
df2 = pd.read_excel('Travel.xlsx', sheet_name = 2)
df2.head()

,주요재무정보,2019/09\n(IFRS연결),2019/12\n(IFRS연결),2020/03\n(IFRS연결),2020/06\n(IFRS연결),2020/09\n(IFRS연결),2020/12(E)\n(IFRS연결),2021/03(E)\n(IFRS연결),2021/06(E)\n(IFRS연결)
0,매출액,4055.0,3728.0,2360.0,346.0,766.0,1581.0,1473.0,1746.0
1,영업이익,1392.0,641.0,-1868.0,-1038.0,-649.0,-434.0,-187.0,-65.0
2,영업이익(발표기준),1392.0,641.0,-1868.0,-1038.0,-649.0,NaN,NaN,NaN
3,세전계속사업이익,1554.0,769.0,-2204.0,-723.0,-552.0,-331.0,NaN,NaN
4,당기순이익,1286.0,526.0,-1561.0,-456.0,-409.0,-465.0,NaN,NaN

In [ ]:
df = df1.append(df2, ignore_index = True)
df.shape

(64, 9)

##### **Q1. `df1`의 shape을 쓰세요.**

In [ ]:
print(df1.shape)

(32, 9)

##### **Q2. `df2`의 shape을 쓰세요.**

In [ ]:
print(df2.shape)

(32, 9)

### **1-2. 결측치 확인**

- df1과 df2의 결측치를 확인하세요.
  - 두 데이터 프레임의 결측치 확인 후, 
[.fillna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html) 메서드를 활용하여 결측치를 0으로 대체하세요. <br>
- 결측치 대체 후에 제대로 코드가 작동 하였는지 확인하도록 합니다.

In [ ]:
df1.fillna(0)
df2.fillna(0)

,주요재무정보,2019/09\n(IFRS연결),2019/12\n(IFRS연결),2020/03\n(IFRS연결),2020/06\n(IFRS연결),2020/09\n(IFRS연결),2020/12(E)\n(IFRS연결),2021/03(E)\n(IFRS연결),2021/06(E)\n(IFRS연결)
0,매출액,4055.00,3728.00,2360.00,346.00,766.00,1581.00,1473.0,1746.00
1,영업이익,1392.00,641.00,-1868.00,-1038.00,-649.00,-434.00,-187.0,-65.00
2,영업이익(발표기준),1392.00,641.00,-1868.00,-1038.00,-649.00,0.00,0.0,0.00
3,세전계속사업이익,1554.00,769.00,-2204.00,-723.00,-552.00,-331.00,0.0,0.00
4,당기순이익,1286.00,526.00,-1561.00,-456.00,-409.00,-465.00,0.0,0.00
5,당기순이익(지배),1286.00,526.00,-1561.00,-456.00,-409.00,-314.00,-33.0,135.00
6,당기순이익(비지배),0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
7,자산총계,41698.00,44381.00,43702.00,39178.00,37434.00,38271.00,0.0,0.00
8,부채총계,4781.00,7204.00,9945.00,5900.00,4560.00,5998.00,0.0,0.00
9,자본총계,36917.00,37178.00,33757.00,33277.00,32875.00,32274.00,0.0,0.00
10,자본총계(지배),36916.00,37177.00,33757.00,33277.00,32874.00,32212.00,0.0,0.00
11,자본총계(비지배),0.00,0.00,0.00,1.00,0.00,0.00,0.0,0.00
12,자본금,1070.00,1070.00,1070.00,1070.00,1070.00,1070.00,0.0,0.00
13,영업활동현금흐름,-22.00,2067.00,-684.00,-3070.00,-1584.00,0.00,0.0,0.00
14,투자활동현금흐름,-1260.00,-2370.00,909.00,5414.00,2327.00,0.00,0.0,0.00
15,재무활동현금흐름,-4.00,-4.00,-4.00,-1842.00,-4.00,0.00,0.0,0.00
16,CAPEX,167.00,383.00,124.00,82.00,260.00,0.00,0.0,0.00
17,FCF,-189.00,1684.00,-808.00,-3153.00,-1844.00,0.00,0.0,0.00
18,이자발생부채,48.00,680.00,651.00,639.00,646.00,0.00,0.0,0.00
19,영업이익률,34.33,17.18,-79.14,-299.75,-84.68,-27.49,-12.7,-3.72
20,순이익률,31.72,14.11,-66.15,-131.55,-53.33,-29.42,0.0,0.00
21,ROE(%),8.27,9.16,2.21,-0.59,-5.44,0.00,0.0,0.00
22,ROA(%),7.20,7.72,1.75,-0.50,-4.80,0.00,0.0,0.00
23,부채비율,12.95,19.38,29.46,17.73,13.87,18.58,0.0,0.00
24,자본유보율,3513.86,3538.24,3218.48,3173.64,3136.00,0.00,0.0,0.00
25,EPS(원),601.00,246.00,-730.00,-213.00,-191.00,-147.00,-15.0,63.00
26,PER(배),21.00,18.92,55.53,0.00,0.00,0.00,0.0,0.00
27,BPS(원),18209.00,18337.00,16650.00,16414.00,16215.00,15888.00,0.0,0.00
28,PBR(배),1.62,1.61,1.19,1.31,1.33,1.46,0.0,0.00
29,현금DPS(원),0.00,900.00,0.00,0.00,0.00,0.00,0.0,0.00
30,현금배당수익률,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00
31,현금배당성향(%),0.00,346.75,0.00,0.00,0.00,0.00,0.0,0.00

##### **Q3. `df1`의 -1번째 column의 결측치는 모두 몇 개인지 구하세요.**

In [4]:
df1.isnull().sum()

주요재무정보                   0
2019/09\n(IFRS연결)        1
2019/12\n(IFRS연결)        1
2020/03\n(IFRS연결)        2
2020/06\n(IFRS연결)        3
2020/09\n(IFRS연결)        4
2020/12(E)\n(IFRS연결)    16
2021/03(E)\n(IFRS연결)    24
2021/06(E)\n(IFRS연결)    24
dtype: int64

##### **Q4. `df2`의 -1번째 column의 결측치는 모두 몇 개인지 구하세요.**

In [7]:
df2.isnull().sum()

주요재무정보                   0
2019/09\n(IFRS연결)        2
2019/12\n(IFRS연결)        2
2020/03\n(IFRS연결)        4
2020/06\n(IFRS연결)        3
2020/09\n(IFRS연결)        4
2020/12(E)\n(IFRS연결)    16
2021/03(E)\n(IFRS연결)    27
2021/06(E)\n(IFRS연결)    27
dtype: int64

In [ ]:
set(df1.columns) == set(df2.columns)

True

### **1-3. GitHub Pull Request**

> 아래 **`🥇 도전과제`**를 풀 경우, 도전과제까지 모두 마친 후 이 문항을 마지막에 수행합니다. 

- 다음 링크를 통해 chrome에 **`open in colab`**을 설치합니다. <br>
  https://chrome.google.com/webstore/detail/open-in-colab/iogfkhleblhcpcekbiedikdehleodpjo
- colab에서 **`도구`** > **`설정`** > **`GitHub`** 으로 이동해 **`비공개 저장소 및 조직에 액세스`**에 체크합니다. <br>
  https://colab.research.google.com/
- 유어클래스의 **`[AIB] Archives`** > **`AI 부트캠프 DOCs`** > **`1. Colab 을 통한 Pull Request 과제제출`**을 참고하여 깃헙에 n111a를 PR합니다. <br>
  https://urclass.codestates.com/content/a18a5115-f614-49ab-810a-87f5024c3297?playlist=2461
- **`변경사항 설명 메세지`**에는 **`[n111a] 1차 제출`** 이라고 씁니다.

# **🥇 도전 과제**

## **Part 2. Missing Value**

##### **자산총계의 결측치를 처리하세요.**
앞선 문제에서는 결측치를 단순히 0으로 처리하였으나, 결측치를 처리하는 방법은 그 외에도 여러가지가 있습니다. <br>
다양한 imputation 방법에 대해 알아보고, 그 중 mean imputation 방법을 사용하여 `자산총계`의 결측치를 처리해보세요.

In [8]:
df1.iloc[:,0:9]=df1.iloc[:,0:9].fillna('NaN')
df2.iloc[:,0:9]=df2.iloc[:,0:9].fillna('NaN')

In [9]:
df1.isnull().sum()

주요재무정보                  0
2019/09\n(IFRS연결)       0
2019/12\n(IFRS연결)       0
2020/03\n(IFRS연결)       0
2020/06\n(IFRS연결)       0
2020/09\n(IFRS연결)       0
2020/12(E)\n(IFRS연결)    0
2021/03(E)\n(IFRS연결)    0
2021/06(E)\n(IFRS연결)    0
dtype: int64

In [10]:
df2.isnull().sum()

주요재무정보                  0
2019/09\n(IFRS연결)       0
2019/12\n(IFRS연결)       0
2020/03\n(IFRS연결)       0
2020/06\n(IFRS연결)       0
2020/09\n(IFRS연결)       0
2020/12(E)\n(IFRS연결)    0
2021/03(E)\n(IFRS연결)    0
2021/06(E)\n(IFRS연결)    0
dtype: int64

## **Part 3.Feature Engineering**

##### **`부채 비율 2` 라는 새로운 피쳐를 생성하세요.**

> 부채 비율(%) = (부채총액 / 자본총액) x 100

위의 공식을 활용하여 `부채 비율 2` 라는 column을 생성합니다. 그리고, 생성한 column과 기존 `부채 비율` column의 값이 동일한지 확인해봅니다.

In [ ]:
df1 = pd.DataFrame(columns=range(10))

##### **`종목` 이라는 새로운 피쳐를 생성하세요.**

**`.repeat()`**를 활용하여 새로운 `종목`이라는 새로운 column을 생성합니다.
  - `df1`의 `종목` column에는 `008770` 문자열이 담기도록 합니다.  
  - `df2`의 `종목` column에는 `035250` 문자열이 담기도록 합니다. 

각각의 데이터 프레임에 `종목`이라는 column을 만든 후, 최종적으로 두 데이터프레임 `df1`과 `df2`를 **`.append()`**를 활용하여 합쳐주도록 합니다.

In [ ]:
# 이곳에 코드를 작성하세요.